#Base de datos local
#spring.datasource.url=jdbc:postgresql://localhost:5432/listaCompra?useSSL=false
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#Base de datos servidor
spring.datasource.url=jdbc:postgresql://pg-7082bea-pulako-6ed9.d.aivencloud.com:21133/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_J_kp9LwzoApWZNh1L8O
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.initialization-fail-timeout=0
spring.datasource.hikari.pool-name=HikariPool
spring.datasource.hikari.connection-timeout=1500
spring.datasource.hikari.idle-timeout=5000
spring.datasource.hikari.max-lifetime=30000
server.port=${PORT:8080}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL10Dialect
#Cambiar a update para produccion
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.hibernate.ddl-auto=update
#Con el none como valor, la base de datos no actualiza las modificaciones. Poner a update si quiero hacer alguna modificaci?n
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.hbm2ddl.auto=none
logging.level.org.hibernate.SQL=debug
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
#spring.main.lazy-initialization=true
server.tomcat.max-threads=5
server.tomcat.min-spare-threads=1
#AWS configuracion
endpointUrl = https://s3.cloudLocation.amazonaws.com
accessKey = AKIAT2EIRFYYR3ZGL7U6
secretKey = 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
bucketName = hacercomprasencilla